# Utilisation d'une image Node.js officielle comme base
FROM node:20-alpine

RUN npm install -g pnpm

# Création et définition du répertoire de travail
WORKDIR /app

# Copie des fichiers de dépendances
COPY Server/package*.json ./

# Installation des dépendances
RUN pnpm install

# Copie du reste des fichiers du projet
COPY Server .

# Exposition du port utilisé par l'application
EXPOSE 3000

# Commande pour démarrer l'application en développement
CMD ["pnpm", "run", "dev"]