# Utilisation d'une image Node.js officielle comme base
FROM node:20-alpine

# Création et définition du répertoire de travail
WORKDIR /app

# Copie des fichiers de dépendancesdok
COPY Client/package*.json ./

# Installation des dépendances
RUN npm install

# Copie du reste des fichiers du projet
COPY Client .

# Exposition du port utilisé par l'application
EXPOSE 8080

# Commande pour démarrer l'application en développement
CMD ["npm", "run", "dev"]